# Singular Value Decomposition

In [7]:
import numpy as np

In [11]:
A = np.array([[2,1],[1,2]])
A

array([[2, 1],
       [1, 2]])

In [8]:
eval3, evec3 = np.linalg.eig(A)
np.round(eval3,2)

array([3., 1.])

In [9]:
evec3

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [12]:
B = np.array([[2,3,4],[1,5,0]])
B

array([[2, 3, 4],
       [1, 5, 0]])

In [27]:
C = B.T
C

array([[2, 1],
       [3, 5],
       [4, 0]])

In [28]:
bbt = B@C
bbt

array([[29, 17],
       [17, 26]])

In [29]:
btb = C@B
btb

array([[ 5, 11,  8],
       [11, 34, 12],
       [ 8, 12, 16]])

In [33]:
eval1, evec1 = np.linalg.eig(bbt)
np.round(eval1,2)

array([44.57, 10.43])

In [34]:
evec1

array([[ 0.73752756, -0.67531703],
       [ 0.67531703,  0.73752756]])

In [35]:
eval2, evec2 = np.linalg.eig(btb)
np.round(eval2,2)

array([44.57,  0.  , 10.43])

In [36]:
evec2

array([[ 0.32211546,  0.92747779,  0.18980669],
       [ 0.83723059, -0.18549556, -0.51442816],
       [ 0.4419124 , -0.32461723,  0.83626377]])

In [11]:
np.round(eval2,decimals=2)

array([44.57,  0.  , 10.43])

In [12]:
evec2[:,[1,2]]=-evec2[:,[2,1]]
evec2

array([[ 0.32211546, -0.18980669, -0.92747779],
       [ 0.83723059,  0.51442816,  0.18549556],
       [ 0.4419124 , -0.83626377,  0.32461723]])

In [13]:
sigma = np.array([[eval1[0]**0.5,0,0],[0,eval1[1]**0.5,0]])
sigma

array([[6.67578072, 0.        , 0.        ],
       [0.        , 3.23016282, 0.        ]])

In [14]:
sigma = [[eval1[0]**0.5,0,0],[0,eval1[1]**0.5,0]]
sigma

[[6.67578071583212, 0, 0], [0, 3.2301628185161175, 0]]

In [15]:
np.round(evec1 @ sigma @ evec2.T,decimals = 3)

array([[2., 3., 4.],
       [1., 5., 0.]])

Verified, now we verify for the decomposition in several terms

In [16]:
vec11=np.array(evec1[:,0])
vec11

array([0.73752756, 0.67531703])

In [17]:
vec12=np.array(evec2[:,0])
vec12

array([0.32211546, 0.83723059, 0.4419124 ])

In [18]:
matr1 = (eval1[0]**0.5)*np.dot(vec11[:,None],vec12[None,:])
matr1

array([[1.58595874, 4.12216534, 2.17578762],
       [1.45218294, 3.77446025, 1.9922597 ]])

In [19]:
vec21=np.array(evec1[:,1])
vec21

array([-0.67531703,  0.73752756])

In [20]:
vec22=np.array(evec2[:,1])
vec22

array([-0.18980669,  0.51442816, -0.83626377])

In [21]:
matr2 = (eval1[1]**0.5)*np.dot(vec21[:,None],vec22[None,:])
matr2

array([[ 0.41404126, -1.12216534,  1.82421238],
       [-0.45218294,  1.22553975, -1.9922597 ]])

In [22]:
np.round(matr1+matr2,decimals=3)

array([[2., 3., 4.],
       [1., 5., 0.]])

Using SVD from numpy

In [23]:
U, s, V = np.linalg.svd(B) 

In [24]:
S=[[s[0],0,0],[0,s[1],0]]
np.round(U@ S @V,decimals=3)

array([[ 2.,  3.,  4.],
       [ 1.,  5., -0.]])

In [13]:
0.912**12 + 12*0.088*(0.912**11)

0.7144442013411114